### ISSUE TITLE
Error: Alfred preferences not found at location /Users/xxx/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist

### ISSUE THREAD

**Issue by W-quan** [SamVerschueren/alfred-fkill#10]
alfred-fkill@0.4.0 postinstall /usr/local/lib/node_modules/alfred-fkill
> alfy-init

{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/wzq/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-fkill/node_modules/resolve-alfred-prefs/index.js:15:10)
    at <anonymous>

    at Promise.all.then.arr (/usr/local/lib/node_modules/alfred-fkill/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Alfred preferences not found at location /Users/wzq/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-fkill/node_modules/resolve-alfred-prefs/index.js:15:10)\n    at <anonymous>\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-fkill@0.4.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alfred-fkill@0.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by SamVerschueren** [comment]
Are you using Alfred 3? If so, where are your preferences stored?

**Comment by W-quan** [comment]
![1524626566178](https://user-images.githubusercontent.com/9608466/39224663-02adede6-487b-11e8-8c8d-6beb37c58c92.jpg)


**It is exist**

**Comment by SamVerschueren** [comment]
This is very weird. @sindresorhus Any idea what could cause this?

**Comment by ARISTODE** [comment]
Same problem here...  Any new progress.

**Comment by chieft8** [comment]
same error here

**Comment by Yuzeyang** [comment]
same error here

**Comment by methodik** [comment]
Yep I have the same error

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/4059489/48358698-3c3cd200-e693-11e8-9ffb-7bdfb63f3793.png">

**Comment by suboyang** [comment]
![image](https://user-images.githubusercontent.com/4099914/54422435-76a1a300-4749-11e9-84d7-e02b5006e5c9.png)

 same error!!!!!

**Comment by AndrejTetak** [comment]
same error here

**Comment by W-quan** [comment]
I have notice the "\n". Is it lead to?

**Comment by slebedev** [comment]
Same problem as described in this issue, but I have Alfred Preferences plist by the following path:

```bash
~ $ find . -iname "*Alfred-Preferences*" -type f
./Library/Preferences/com.runningwithcrayons.Alfred-Preferences.plist
```

Is there any workaround? I'm using Alfred4

**Comment by slebedev** [comment]
Workaround for me until this issue isn't resolved:

```bash
~ $ git --work-tree=$(npm root -g)/alfred-fkill clone https://github.com/SamVerschueren/alfred-fkill.git ~/alfred-workflows-git/alfred-fkill
~ $ cd $(npm root -g)/alfred-fkill
alfred-fkill $ npm install alfy fkill pid-from-port ps-list
```

It's an ugly workaround, but it's because I need this workflow working. =) What's going on in commands above:

1. Clone repository with alfred-fkill to `~/alfred-workflows-git/alfred-fkill` path, but all content will be stored in `alfred-fkill` directory in global modules path by `--work-tree=$(npm root -g)/alfred-fkill` option.
2. Than we need open directory with fetched contents
3. And install all dependencies this module uses: `alfy`, `fkill`, `pid-from-port` and `ps-list`. As I don't use `-g` option, all dependencies will be installed in current folder (which is alfred-fkill directory in global npm modules path)

**Comment by SamVerschueren** [comment]
It should be resolved. We made changes to the underlying `alfy` package. Let me know if it isn't.
