### ISSUE TITLE
Why not release an .alfredworkflow file? 

### ISSUE THREAD

**Issue by ghost** [SamVerschueren/alfred-fkill#11]
Why not release an .alfredworkflow file?

**Comment by jorgenbs** [comment]
Agreed, it would be nice with an alternative approach to npm (which doesn't work for me) or manual install instructions

**Comment by sindresorhus** [comment]
We prefer the npm approach.

**Comment by JesusTheHun** [comment]
@sindresorhus while I understand the pros and cons of distribution only through `npm`, as someone who uses `nvm`, it is complicated for me to use this distribution channel.

There is a GitHub Action to automatically build a `.alfredworkflow` and create a release that includes it.
See https://github.com/marketplace/actions/build-an-alfred-workflow.

Would you be willing to accept a PR for that ?
