### ISSUE TITLE
process without vscode

### ISSUE THREAD

**Issue by SadWood** [SamVerschueren/alfred-fkill#15]
input 'kill code' or 'kill visual'
out nothing

**Comment by sindresorhus** [comment]
Please elaborate. Not clear what you’re saying.

**Comment by SadWood** [comment]
> Please elaborate. Not clear what you’re saying.

I want to kill the vscode process, but when I enter code or visual, I don't show the corresponding APP.
thx.

**Comment by aparajita** [comment]
Yeah, for some reason the Code application process itself doesn't show up in the process list (but all of the helper processes do).

**Comment by chrisspiegl** [comment]
Same here, the Visual Studio Code shows all kinds of GPU and Render processes but the main process does not show up.
