### ISSUE TITLE
Keyword 'kill' not activated in alfred4

### ISSUE THREAD

**Issue by ddxgz** [SamVerschueren/alfred-fkill#16]
Hi, 

I installed this workflow using `npm` and the installation is successful. But the keyword `kill` is not activated in alfred4, it only lists items contain the literal text kill. 

Is this due to alfred version consistency issue or did I miss something? Thanks.

**Comment by macx** [comment]
It's looking for Alfred 3 preferences. @SamVerschueren Could you please tweek your workflow in order to work with 4 please?

**Comment by oalders** [comment]
I just noticed this as well.  It would be great to have this working in version 4.

**Comment by SamVerschueren** [comment]
@macx We updated Alfy under the hood (which powers these npm workflows), and it should now be installable on Alfred 4.

Not sure why it doesn't activate though 🤔. If you open Alfred, is it listed as workflow?

**Comment by macx** [comment]
Seems to work now…

**Comment by SamVerschueren** [comment]
I'm closing this. Probably the keyword didn't activate because it was successfully installed, but not linked to Alfred due to lack of support for Alfred 4.

I'll close this for now. Feel free to comment if it still doesn't work for you.
