### ISSUE TITLE
Smart sorting

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/alfred-fkill#2]
If I search for `su`, I get a lot of unrelated processes, when I really wanted `Sublime`. Would be nice to sort by the common case. I imagine we could do something like this priority:

- Apps
- Known binaries like: node, python, etc
- The rest

**Comment by SamVerschueren** [comment]
Yes I agree. So basically we should put everything that ends in `.app` in the beginning, then a custom list of ourselves, and then all the rest?

**Comment by sindresorhus** [comment]
Yes
