### ISSUE TITLE
Cannot find module './lib/util'

### ISSUE THREAD

**Issue by purplecones** [SamVerschueren/alfred-fkill#3]
running `npm install --global alfred-fkill` and trying to kill process from Alfred, I get this error:

```
Error: Cannot find module './lib/util'
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-fkill/index.js:4:14)
```
fkill 0.2.0
Alfred 3.3.1
darwin x64 16.3.0

**Comment by SamVerschueren** [comment]
Darn, you're right. Released `v0.2.1`.
