### ISSUE TITLE
Usage with `nvm`

### ISSUE THREAD

**Issue by elzii** [SamVerschueren/alfred-fkill#8]
Perhaps this is an issue that applies more to nvm or Alfred itself, but is there a recommended workaround for when node is not present at `/usr/local/bin/node`, but a path managed by NVM?

Here's the error thrown.

<img width="593" alt="screen shot 2018-03-17 at 9 30 41 pm" src="https://user-images.githubusercontent.com/1827950/37562619-c24515e0-2a2a-11e8-85e6-1a98c0cf4277.png">

I could symlink it manually but it would be defunct when I switch node versions...

**Comment by SamVerschueren** [comment]
I'm using nvm as well and it works. You should report an issue in the [alfy](https://github.com/sindresorhus/alfy) repository instead. A similar issue was reported [here](https://github.com/sindresorhus/alfy/issues/73).
